### ISSUE TITLE
Working group call #10

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#35] opened 2020-04-22 17:09 UTC
Date/time: Wednesday, April 29, 2020, 7am PT/10am ET/2pm UTC/4pm CEST/10pm CST ([time zone conversion](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Stacks+Governance+Working+Group+Call&iso=20200429T10&p1=179&ah=1))
Location: Link will be posted in [#governance working group channel](https://discordapp.com/invite/ny6wGkx) on Discord shortly before the call
Recording: TBA
Moderator: @joberding 

If you'd like to be added to the recurring calendar invitation, please request one on the working group channel.

Proposed agenda (feel free to amend!):
- What happened over the past week? Standup!
  - What is everyone working on right now?
  - Any blockers?
  - What will happen over the next week?
- Community survey
  - Went out with quarterly newsletter a few days ago
  - 52 total responses now
  - Next steps?
- Blog post outline
  - @whoabuddy [project board](https://github.com/stacksgov/pm/projects/2) and issue label. Need people to comment! (#26)
- Community observer role for Blockstack PBC research calls (#17)
- Code of Conduct (blockstack/stacks-blockchain#1436), governance "due process" in general
- SIPs process proposal
- Stacks Foundation update (from PBC)
- Any other updates/topics?

**Comment by whoabuddy** [comment] 2020-04-23 18:11
We should discuss #17 and how we can implement it in an official capacity.

**Comment by lrettig** [comment] 2020-04-29 13:19
> We should discuss #17 and how we can implement it in an official capacity.

Added to the agenda!

**Comment by whoabuddy** [comment] 2020-04-29 13:34
I'm going through the Call 3 notes and noticed #11, we have it marked as Done on the board but the issue is still open - might be good to review against where we are actually at?

My real question is - do we need to keep it open or can we close it? I know some of the questions are answered by the proposal issues, but it might be worth keeping open, too. I am curious what the group thinks.

**Comment by whoabuddy** [comment] 2020-04-29 16:34
Closing in favor of #37

**Closed by whoabuddy** 2020-04-29 16:34 UTC
Labels: call
